# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CommunityPower EA
email: komposter@gmail.com
author: komposter
description: > # this means to ignore newlines until "baseurl:"
  Free, Versatile and Powerful Expert Advisor for MetaTrader 4/5

# Add your baseurl here (your repository) but DO NOT CHANGE THE LINE NUMBER without editing .circleci/circle_urls.sh
baseurl: "" # the subpath of your site, e.g. /blog

# This is mostly for testing
url: "https://communitypowerea.com" # the base hostname & protocol for your site

# Social (First three Required)
repo: "https://github.com/komposter/CommunityPowerEA.com"
github_user: "komposter"
github_repo: "CommunityPowerEA.com"
github_branch: "gh-docsy"

# Optional
#twitter: vsoch
#linkedin: vsochat
#dockerhub: vanessa

## These options are used to configure the locations of your version history when you want to serve versioned documents
#version_params:
#  version_menu: "Release"
#  version_dir: Archive
#  tocversion_dir: versions
#  versioning: false
#
#  # Disable so older versions cannot be searched
#  allow_search: true
#
#  # Allow these versions to be searched
#  search_versions:
#    - Previous
#  latest: Current
#  versions:
#    - Current
#    - Previous

# Should there be feedback buttons at the bottom of pages?
feedback: false

# Link to a privacy policy in footer, uncomment and define if wanted
# privacy: https://domain.com/privacy

google-analytics: G-ZKBYQNPTE1
# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
logo: "assets/img/logo_square_1.png"
logo_pixels: 32
color: "#403f4c" # primary color for header, buttons

# Build settings
markdown: kramdown

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'false' # true or false

permalink: /:year/:title/
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
